"""DocStrings in an __init__ file will be written to the Module Contents section of auto-code documentation
generated by Sphinx.  In our guide we also list the module contents before the submodule.  This is not the default
but can be generated with autodoc using the --module-first option. Or, of course, you can also manually edit the
rst file for the module."""

# PEP8: Group imports
# 1) Standard library imports.
# 2) Related third party imports.
# 3) Local application/library specific imports.
